common/urls.py
from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from pec import views

urlpatterns = [
    path('', views.HomeViewFE.as_view(), name='home'),
    path('admin/', admin.site.urls),

    path('index_fe/', views.HomeViewFE.as_view(), name='index-fe'),
    path('index_mp/', views.HomeViewMP.as_view(), name='index-mp'),
    path('comp_prof_liste/', views.CompetenceProfListView.as_view(), name='competence-prof-liste'),
    path('comp_prof/<int:pk>/', views.CompetenceProfView.as_view(), name='competence-prof'),
    path('comp_metho/<int:pk>/', views.CompetenceMethoView.as_view(), name='competence-metho'),
    path('comp_perso/<int:pk>/', views.CompetencePersoView.as_view(), name='competence-perso'),
    path('cours/<int:pk>/', views.CoursDetailView.as_view(), name='cours'),
    path('cours_admin/<int:pk>/', views.CoursAdminView.as_view(), name='cours-admin'),
    path('periode_fe/', views.PeriodeView.as_view(), {'filiere': 'FE'}, name='periode-fe'),
    path('periode_mp/', views.PeriodeView.as_view(), {'filiere': 'MP'}, name='periode-mp'),
    path('periode_domaine_fe/', views.PeriodeDomaineView.as_view(), {'filiere': 'FE'}, name='periode-domaine-fe'),
    path('periode_domaine_mp/', views.PeriodeDomaineView.as_view(), {'filiere': 'MP'}, name='periode-domaine-mp'),
    path('seminaire/', views.SeminaireView.as_view(), name='seminaire'),
    path('cours/', views.CoursFEListView.as_view(), name='cours'),
    path('obj_eval/', views.ObjectifParticulierListView.as_view(), name='obj-eval-liste'),
    path('json_objeval/<int:pk>/', views.json_objeval),
    path('plan_pdf_fe/', views.plan_form_pdf, {'filiere': 'FE'}, name='plan-pdf-fe'),
    path('plan_pdf_mp/', views.plan_form_pdf, {'filiere': 'MP'}, name='plan-pdf-mp'),
    path('documents/', views.DocumentListView.as_view(), name='documents'),
    path('document/<int:pk>/', views.DocumentDetailView.as_view(), name='document-detail'),
    
    # url(r'^json_objeval/(?P<pk>\d+)$', views.json_objeval),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pec/models.py
import os

from django.db import models
from django.conf import settings

# Create your models here.
CHOIX_ORIENTATION = (
    ('Global', 'Global'),
    ('Gén.', 'Gén.'),
    ('Enf.', 'Enf.'),
    ('PersA', 'PersA'),
    ('Hand.', 'Hand.'))


class Orientation(models.Model):
    nom = models.CharField(max_length=10, default="Global", choices=CHOIX_ORIENTATION)
    
    def __str__(self):
        return self.nom


class Taxonomie(models.Model):
    code = models.CharField(max_length=5, blank=False)
    descr = models.TextField(default='', blank=True, verbose_name='description')

    class Meta:
        ordering = ('code',)

    def __str__(self):
        return '{0}'.format(self.code)


class Domaine(models.Model):
    code = models.CharField(max_length=8, blank=False)
    nom = models.CharField(max_length=100, blank=False, unique=True)
    descr = models.TextField('description', default='', blank=True)
    abrev = models.CharField('abréviation', max_length=10, blank=True)
    couleur = models.CharField(max_length=10, default='', blank=True)
    
    class Meta:
        ordering = ('code',)

    def __str__(self):
        return '{0} -{1}'.format(self.code, self.nom)

    def cours_fe_annee_1(self):
        return self.cours_set.filter(cursus__code='1FE').exclude(index_published=False)

    def cours_fe_annee_2(self):
        return self.cours_set.filter(cursus=2).exclude(index_published=False)

    def cours_fe_annee_3(self):
        return self.cours_set.filter(cursus=3).exclude(index_published=False)

    def cours_mp_annee_1(self):
        return self.cours_set.filter(cursus=4).exclude(index_published=False)

    def cours_mp_annee_2(self):
        return self.cours_set.filter(cursus=5).exclude(index_published=False)

    def cours_mp_annee_3(self):
        return self.cours_set.filter(cursus=6).exclude(index_published=False)    


class TypeCompetence(models.Model):
    nom = models.CharField(max_length=80)

    def __str__(self):
        return self.nom


class Competence(models.Model):
    """Compétence de base selon PEC """
    code = models.CharField(max_length=8, blank=False)
    nom = models.CharField(max_length=150, blank=True)
    descr = models.TextField(default='', blank=True, verbose_name='description') 
    domaine = models.ForeignKey(Domaine, null=True, on_delete=models.SET_NULL)

    class Meta:
        ordering = ('code',)
        verbose_name = 'Compétence'

    def __str__(self):
        return '{0} -{1}'.format(self.code, self.nom)


class CompetenceTransversale(models.Model):
    """Compétence transversale selon PEC-ASE (méthodologiques et personnelles)"""
    nom = models.CharField(max_length=150)
    type = models.ForeignKey(TypeCompetence, default=None, blank=False, null=True, on_delete=models.SET_NULL)
    
    class Meta:
        verbose_name = 'Comp. transversale'
        ordering = ('id',)
        
    def __str__(self):
        return self.nom    
    
      
class ObjectifParticulier(models.Model):
    """Objectif particulier selon PEC-ASE (24 obj. part.)"""
    tri = models.IntegerField(default=0)
    code = models.CharField(max_length=8, blank=False)
    nom = models.CharField(max_length=250, blank=True)
    competence = models.ForeignKey(Competence, default=None, null=True, blank=True, on_delete=models.SET_NULL)
    competences_transversales = models.ManyToManyField(CompetenceTransversale, blank=True)
    
    class Meta:
        ordering = ('tri',)
        verbose_name = 'Obj. particulier'
        verbose_name_plural = 'Obj. particuliers'
        
    def __str__(self):
        return '{0} -{1}'.format(self.code, self.nom)
    
    
class ObjectifEvaluateur(models.Model):
    """Objectif éval. selon PEC-ASE (278 obj. part.)
    Ne garder que les objectifs Globaux et Gén.
    """
    tri = models.IntegerField(default=0)
    code = models.CharField(max_length=8, blank=False)
    nom = models.TextField(default='', blank=True)
    objectif_particulier = models.ForeignKey(ObjectifParticulier, null=True, default=None, blank=True, on_delete=models.SET_NULL)
    taxonomie = models.ForeignKey(Taxonomie, null=True, default=None, blank=True,  on_delete=models.SET_NULL)
    orientation = models.ForeignKey(Orientation, null=True, default=None, blank=True, on_delete=models.SET_NULL)
    
    class Meta:
        unique_together = ('id', 'orientation')
        ordering = ('tri', )
        verbose_name = 'Obj. évaluateur'
        verbose_name_plural = 'Obj. évaluateurs'
    
    def __str__(self):
        return '{0}-{1}-{2}'.format(self.code, self.orientation.nom[:3], self.nom[:20])    
        
        
class Cursus(models.Model):
    """ Regroupe l'année et dormation et la filière
        Ex: 1MP, 3FE, etc
    """
    code = models.CharField(max_length=10, blank=False, unique=True)
     
    def __str__(self):
        return self.code

    class Meta:
        ordering = ('code', )
        verbose_name_plural = 'Cursus'

    
class Cours(models.Model):
    """ Cours de la formation ASE"""
    nom = models.CharField(max_length=40, blank=False)
    descr = models.TextField(blank=True, verbose_name='description')
    objectifs_evaluateurs = models.ManyToManyField(ObjectifEvaluateur, blank=True)
    type = models.CharField(max_length=30, blank=True)
    periode = models.IntegerField()
    nbre_note = models.IntegerField()
    domaine = models.ForeignKey(Domaine, default=None,  null=True, blank=True, on_delete=models.SET_NULL)
    careum = models.CharField(max_length=30, default='')
    cursus = models.ManyToManyField(Cursus, blank=True)
    index_published = models.BooleanField(default=True)
    evaluation = models.CharField(max_length=150, blank=True)
    didactique = models.CharField(max_length=150, blank=True)
    # cursus = models.CharField(max_length=20, blank=True)
    
    class Meta:
        # unique_together = ('nom', 'periode')
        ordering = ('nom',)
        verbose_name_plural = 'Cours'
         
    def __str__(self):
        return '{0}'.format(self.nom)
     
    def formation(self):
        # foo = [x.code for x in self.cursus.all()]
        return ', '.join([x.code for x in self.cursus.all()])
    
    def get_cursus(self):
        foo = [x.code for x in self.cursus.all()]
        print(foo)
        return ', '.join(foo)

    def get_objectifs_evaluateurs(self):
        bar = []
        for sequence in self.sequence_set.all():
            for obj in sequence.objectifs_evaluateurs.all().order_by('tri'):
                bar.append(obj.id)
        bar.sort()
        return ObjectifEvaluateur.objects.filter(id__in=bar).order_by('tri')


class Sequence(models.Model):
    """Séquence pédagogique à l'intérieur d'un cours"""
    titre = models.CharField(max_length=100, blank=False)
    cours = models.ForeignKey(Cours, on_delete=models.CASCADE)
    periode = models.IntegerField(blank=False)
    contenu = models.TextField(blank=True)
    objectifs_evaluateurs = models.ManyToManyField(ObjectifEvaluateur, blank=True)
    objectifs_apprentissage = models.TextField(blank=True)
    careum = models.CharField(max_length=20, default='', blank=True)
    
    def __str__(self):
        return self.titre

    def get_objectifs_evaluateurs_txt(self):
        foo = [x.code for x in self.objectifs_evaluateurs.all()]
        return ', '.join(foo)


class Document(models.Model):
    """Document à uploader"""
    path = models.FileField(upload_to='doc/')
    titre = models.CharField(max_length=100, blank=False)
    published = models.BooleanField(default=False)
    
    def __str__(self):
        return self.titre    
    
    def delete(self, *args, **kwargs):
        os.remove(os.path.join(settings.MEDIA_ROOT, self.path.name))
        super(Document, self).delete(*args, **kwargs)

pec/views.py
import json
import os
import tempfile

from django.views.generic import DetailView, ListView, TemplateView
from django.http import HttpResponse
from django.db.models import F, Sum

from .forms import CoursProfAdminForm
from .models import (Competence, ObjectifParticulier, 
                     ObjectifEvaluateur, Domaine, Cours, Document)
from pdf.models import PlanFormationPdf


class HomeViewFE(ListView):
    model = Domaine
    template_name = 'pec/index_fe.html'
    
    def get_queryset(self):
        return Domaine.objects.all().exclude(abrev='CIE')


class HomeViewMP(ListView):
    model = Domaine
    template_name = 'pec/index_mp.html'
    
    def get_queryset(self):
        return Domaine.objects.all().exclude(abrev='ECG').exclude(abrev='EPH')
    
    
class CompetenceProfView(DetailView):
    model = Competence
    template_name = 'pec/comp_prof_detail2.html'
    exclude = ('tri',)

    
class CompetenceMethoView(DetailView):
    model = Competence
    template_name = 'pec/comp_metho_detail.html'


class CoursDetailView(DetailView):
    model = Cours
    template_name = 'pec/cours_detail.html'


class CompetencePersoView(DetailView):
    model = Competence
    template_name = 'pec/comp_perso_detail.html'


class CompetenceProfListView(ListView):
    model = Competence
    template_name = 'pec/comp_prof_liste.html'


class ObjectifParticulierListView(ListView):
    model = ObjectifParticulier
    template_name = 'pec/obj_eval_liste.html'
        
    def get_queryset(self):
        return ObjectifParticulier.objects.all()

    
class PeriodeView(TemplateView):
    template_name = 'pec/periode.html'
    
    def get_context_data(self, **kwargs):
        context = super(PeriodeView, self).get_context_data(**kwargs) 
        filiere = self.kwargs['filiere']
        if filiere == 'MP':
            context['cours1'] = Cours.objects.filter(cursus__code='1MP').exclude(index_published=False)
            context['cours2'] = Cours.objects.filter(cursus__code='2MP').exclude(index_published=False)
            context['cours3'] = Cours.objects.filter(cursus__code='3MP').exclude(index_published=False)
            context['toggle'] = 'MP'
            context['formation'] = 'Formation avec matu. prof. intégrée'
        if filiere == 'FE':
            context['cours1'] = Cours.objects.filter(cursus__code='1FE').exclude(index_published=False)
            context['cours2'] = Cours.objects.filter(cursus__code='2FE').exclude(index_published=False)
            context['cours3'] = Cours.objects.filter(cursus__code='3FE').exclude(index_published=False)
            context['toggle'] = 'FE'
            context['formation'] = 'Formation en entreprise'
            
        context['tot1'] = context['cours1'].aggregate(Sum(F('periode')))['periode__sum'] 
        context['tot2'] = context['cours2'].aggregate(Sum(F('periode')))['periode__sum'] 
        context['tot3'] = context['cours3'].aggregate(Sum(F('periode')))['periode__sum'] 
        context['tot'] = context['tot1'] + context['tot2'] + context['tot3']
        return context   
    
    
class PeriodeDomaineView(ListView):
    model = Domaine
    template_name = 'pec/periode_domaine.html'
    
    def get_context_data(self, **kwargs):
        filiere = self.kwargs['filiere']
        context = super(PeriodeDomaineView, self).get_context_data(**kwargs)
        if filiere == 'MP':
            exclude_fields = ['ECG', 'EPH']
            c1 = Cours.objects.filter(cursus__code='1MP').exclude(index_published=False)
            c2 = Cours.objects.filter(cursus__code='2MP').exclude(index_published=False)
            c3 = Cours.objects.filter(cursus__code='3MP').exclude(index_published=False)
            context['formation'] = 'Formation avec matu. prof. intégrée'
            context['toggle'] = 'MP'
        else:
            exclude_fields = ['CIE']
            c1 = Cours.objects.filter(cursus__code='1FE').exclude(index_published=False)
            c2 = Cours.objects.filter(cursus__code='2FE').exclude(index_published=False)
            c3 = Cours.objects.filter(cursus__code='3FE').exclude(index_published=False)
            context['formation'] = 'Formation en entreprise'
            context['toggle'] = 'FE'
        
        dom = []
        for i, d in enumerate(Domaine.objects.all().exclude(abrev__in=exclude_fields)):              
            d.tot1 = c1.filter(domaine=d).aggregate(Sum(F('periode')))['periode__sum']
            d.tot2 = c2.filter(domaine=d).aggregate(Sum(F('periode')))['periode__sum']
            d.tot3 = c3.filter(domaine=d).aggregate(Sum(F('periode')))['periode__sum'] 
            dom.append(d)
        
        context['dom'] = dom
        context['a1'] = c1.aggregate(Sum(F('periode')))['periode__sum']
        context['a2'] = c2.aggregate(Sum(F('periode')))['periode__sum']
        context['a3'] = c3.aggregate(Sum(F('periode')))['periode__sum']
        context['aa'] = context['a1'] + context['a2'] + context['a3']
        return context

             
class SeminaireView(TemplateView):
    template_name = 'pec/seminaire.html'
    

class CoursFEListView(ListView):
    model = Cours
    template_name = 'pec/cours.html'    
    
    def get_queryset(self):
        return Cours.objects.all().order_by('nom')    


class CoursAdminView(DetailView):
    model = Cours
    template_name = 'pec/cours_admin.html'
    form_class = CoursProfAdminForm
    
    def get_context_data(self, **kwargs):
        context = super(CoursAdminView, self).get_context_data(**kwargs)
        context['form'] = CoursProfAdminForm   
        return context


class DocumentListView(ListView):
    model = Document
    # template_name = 'pec/document_list.html'
    
    def get_queryset(self):
        return Document.objects.filter(published=True)


class DocumentDetailView(DetailView):
    model = Document
    template_name = 'pec/document_detail.html'
    

def plan_form_pdf(request, filiere):
    filename = 'plan-formation.pdf'
    path = os.path.join(tempfile.gettempdir(), filename)
    pdf = PlanFormationPdf(path)
    pdf.produce(filiere)
    with open(path, mode='rb') as fh:
        response = HttpResponse(fh.read(), content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename="plan_de_formation.pdf"'
    return response


def json_objeval(request, pk):
    """Retourne les objectifs évaluateurs de l'obj. particulier PK
       et filtre sur les orientation Global et Gén uniquement
    """
    objs = ObjectifEvaluateur.objects.filter(objectif_particulier=pk).filter(orientation__lte=2)
    data = [{'code': o.code,
             'orientation': o.orientation.nom,
             'nom': o.nom,
             'taxonomie': o.taxonomie.code} for o in objs]
    return HttpResponse(json.dumps(data), content_type="application/json")

templates/pec/base_site.html
{% extends "./base.html" %}
{% load static %}
{% block extrastyle %}{% endblock %}
{% block title %}ASE{% endblock %}

{% block branding %}
    <h1 id="site-name">
        <a href="{% url 'home' %}">Ecole Santé-social Pierre-Coullery</a>
        &nbsp;&nbsp;- &nbsp;&nbsp;Formation CFC-ASE</h1>
{% endblock %}
{% block usertools %}
    <div id="user-tools">
        {% if user.is_authenticated %}
            {% block welcome-msg %}
                Bienvenue <strong>{% firstof user.username %}</strong>.
            {% endblock %}
            <a href="{% url 'home' %}">Site public</a>&nbsp;&nbsp;<a href="{% url 'admin:index' %}">Admin</a>
            &nbsp;&nbsp;{% block quick_edit %}{% endblock %}
        {% else %}
            <a href="{% url 'admin:index' %}">Admin</a>
        {% endif %}
    </div>
{% endblock %}
{% block nav-global %}{% endblock %}
{% block breadcrumbs %}
    <div class="breadcrumbs">
        <ul>
            <li><a href="{% url 'home' %}">Accueil</a></li>
            <li><a href="{% url 'competence-prof-liste' %}">Comp. prof.</a></li>
            <li><a href="{% url 'obj-eval-liste' %}">Obj. éval.</a></li>
            <li><a href="{% url 'cours' %}">Cours</a></li>
            <li><a href="{% url 'periode-fe' %}">Pér. formation</a></li>
            <li><a href="{% url 'periode-domaine-fe' %}">Pér. par domaine</a></li>
            <li><a href="{% url 'documents' %}">Documents</a></li>
        </ul>
    </div>
{% endblock %}

templates/pec/comp_metho_detail.html
{% extends "./base_site.html" %}
{% load i18n static %}

{% block coltype %}colMS{% endblock %}

{% block content %}
    <div id="content-main">
        {{object.nom}}<br/>
    </div>
{% endblock %}

templates/pec/comp_prof_detail.html
{% extends "./base_site.html" %}
{% load i18n static %}


{% block coltype %}colMS{% endblock %}

{% block content %}
  <script>
    $( function() {
      $( "#accordion" ).accordion();
    } );
  </script>

  <div id="content-main">
    <h1>Compétences professionnelles</h1>
    <h2>{{object.code}} - {{object.nom}}</h2>
    <br/>
    <h2>Objectifs particuliers</h2>

    <div id="accordion">
      {% for opa in object.objectifparticulier_set.all %}
        <h3>{{opa.code}} - {{opa.nom}}</h3>
        <div>
          <table>
            {% for oev in opa.objectifevaluateur_set.all %}
              {% if oev.orientation.nom == 'Global' or oev.orientation.nom == 'Gén.'  %}
                <tr><td width="100px">{{oev.code}}&nbsp;&nbsp;{{oev.orientation.nom}}</td><td>{{oev.nom}} - ({{oev.taxonomie}})</td></tr>
              {% endif %}
            {% endfor %}
          </table>
        </div>
    {% endfor %}
    </div>
  </div>
{% endblock %}

templates/pec/comp_prof_detail2.html
{% extends "./base_site.html" %}
{% load i18n static %}


{% block coltype %}colMS{% endblock %}

{% block content %}
  <div id="content-main">
    <h1>Compétences professionnelles</h1>
    <h2>{{object.code}} - {{object.nom}}</h2>
    <br/>
    <h2>Objectifs particuliers</h2>

    <div id="accordion">
      {% for opa in object.objectifparticulier_set.all %}
        <h3>{{opa.code}} - {{opa.nom}}</h3>
        <div>
          <table>
            {% for oev in opa.objectifevaluateur_set.all %}
              {% if oev.orientation.nom == 'Global' or oev.orientation.nom == 'Gén.'  %}
                <tr><td width="10px"></td><td width="100px">{{oev.code}}&nbsp;&nbsp;{{oev.orientation.nom}}</td><td>{{oev.nom}} - ({{oev.taxonomie}})</td></tr>
              {% endif %}
            {% endfor %}
          </table>
        </div>
    {% endfor %}
    </div>
  </div>
{% endblock %}

templates/pec/comp_prof_liste.html
{% extends "./base_site.html" %}
{% load i18n static %}

{% block coltype %}colMS{% endblock %}

{% block content %}
    <div id="content-main">
        <h1>Compétences professionnelles</h1>
        <table>
            {% for comp in object_list %}
                <tr>
                    <td>{{comp.code}}</td>
                    <td><a href="{% url 'competence-prof' comp.id %}">{{comp.nom}}</a></td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

templates/pec/cours.html
{% extends "./base_site.html" %}
{% load i18n static %}

{% block coltype %}colMS{% endblock %}

{% block content %}
    <div id="content-main" style="margin-left:200px">
        <h1>Liste des cours</h1>
        <table>
            <tr>
                <th>Nom du cours</th>
                <th>Cursus concerné(s)</th>
                <th style="text-align:right;">Périodes</th>
            </tr>
            {% for c in object_list %}
                <tr>
                    <td><a href="{% url 'cours' c.id %}">{{ c.nom }}</a></td>
                    <td>{{ c.cursus_txt }}</td>
                    <td style="width:100px;text-align:right">{{ c.periode }} pér.</td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

templates/pec/cours_detail.html
{% extends "./base_site.html" %}
{% load i18n static %}
{% block quick_edit %}<a href="{% url 'admin:pec_cours_change' object.id %}">Edit</a>{% endblock %}
{% block coltype %}colMS{% endblock %}

{% block content %}

<div id="content-main">
	<h1>{{object.nom}}</h1>
	{% if user.is_active and user.is_staff %}
		<table >
			<tr>
				<th width="200px">Domaine</th>
				<td>{{object.domaine.nom}}</td>
			</tr>
			<tr>
				<th>Compétence(s) travaillées()</th>
				<td>
					{% for c in object.domaine.competence_set.all %}
						<p>{{c.code}} - {{c.nom}}</p>
					{% endfor %}
				</td>
			</tr>
			<tr>
				<th>Durée</th><td>{{object.periode}} pér.</td>
			</tr>
			<tr>
				<th>Cursus</th>
				<td>{{object.get_cursus}}</td>
			</tr>
			<tr>
				<th>Nbre de notes</th>
				<td>{{object.nbre_note}}</td>
			</tr>
			<tr>
				<th>Careum</th>
				<td>{{object.careum}}</td>
			</tr>
			<tr>
				<th>Séquence</th>
				<td style="padding:0;spacing:0">
					<table>
						<tr>
							<th>Titre</th>
							<th>Périodes</th>
							<th>Careum</th>
							<th>Obj. éval.</th>
						</tr>
						{% for s in object.sequence_set.all %}
							<tr>
								<td>{{ s.titre }} :</td>
								<td>{{ s.periode }} pér.</td>
								<td>{{ s.careum }}</td>
								<td>{% for oa in s.objectifs_evaluateurs.all %}
									{{ oa.code }} - {{oa.orientation }}&nbsp;
									{% endfor %}
								</td>
								<td>{{ s.contenu }}</td>
							</tr>
						{% endfor %}
					</table>
				</td>
			</tr>

			<tr>
				<th>Obj. évaluateurs</th>
				<td style="padding:0;spacing:0">
					<table>
						{% for x in object.get_objectifs_evaluateurs %}
							<tr>
								<th width="100px">{{ x.code }}-{{x.orientation}}:</th>
								<td>{{ x.nom }} ({{x.taxonomie}})</td>
							</tr>
						{% endfor %}
					</table>
				</td>
			</tr>
		</table>
	{% else %}
		En travail...
	{% endif %}
	<br>
</div>
{% endblock %}

templates/pec/document_detail.html
{% extends "./base_site.html" %}
{% load i18n static %}

{% block coltype %}colMS{% endblock %}

{% block content %}
<div id="content-main">
    <h1>{{ object.titre }}</h1>
    <iframe  src="/media/{{object.path}}" width="1200" height="800" align="middle"></iframe>
</div>
{% endblock %}

templates/pec/document_list.html
{% extends "./base_site.html" %}
{% load i18n static %}

{% block coltype %}colMS{% endblock %}

{% block content %}

<div id="content-main">
    <h1>Documents</h1>
    <ul>
        {% for doc in object_list %}
            <li><a href="{% url 'document-detail' doc.id %}">{{doc.titre}}</a></li>
            {% empty %}
            <li>Aucun document disponible</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

templates/pec/en_travail.html
{% extends "./base_site.html" %}
{% load i18n static %}
{% block quick_edit %}<a href="{% url 'admin:pec_cours_change' object.id %}">Edit</a>{% endblock %}
{% block coltype %}colMS{% endblock %}

{% block content %}

<div id="content-main">
<h1>{{object.nom}}</h1>
    En travail...
    <br>
</div>
{% endblock %}

templates/pec/index.html
{% extends "./base_site.html" %}
{% load i18n static %}

{% block coltype %}colMS{% endblock %}

{% block content %}

<div id="content-main">

	<table id="plan">
		<tr>
			<th width="700px">Compétences méthodologiques</th>
			<th width="700px">Compétences professionnelles</th>
			<th width="700px">Compétences personnelles</th>
		</tr>
		<tr>
			<td>
				{% for m in metho %}
					<p>{{forloop.counter}}&nbsp;<a href="{% url 'competence-metho' m.id %}">{{m.nom}}</a></p><br/>
				{% endfor %}
			</td>
			<td>
				{% for c in competences %}
					<p>{{forloop.counter}}&nbsp;<a href="{% url 'competence-prof' c.id %}">{{c.nom}}</a></p><br/>
				{% endfor %}
			</td>
			<td>
				{% for p in perso %}
					<p>{{forloop.counter}}&nbsp;{{p.nom}}</p><br/>
				{% endfor %}
			</td>
		</tr>
	</table>
<br/>
</div>
{% endblock %}

templates/pec/obj_eval_liste.html
{% extends "./base_site.html" %}
{% load i18n static %}

{% block coltype %}colMS{% endblock %}

{% block content %}

<script type="text/javascript">
    $(document).ready(function(){
        $("#obp_selector").on('change', function(){
            $.ajax({
                url : 'json_objeval/' + $(this).val(),
                type : 'GET',
                //data : 'id=' + $(this).val(),
                dataType : 'json',
                success : function(data, statut){
                    var html = '';
                    var sel = $("#json");
                    sel.empty();
                    html = '<table>'
                    $.each(data, function(index) {
                       html += '<tr><td width="100px">' + this.code + ' - ' + this.orientation + '</td>';
                       html += '<td width="800px">' + this.nom
                       html += '</td><td style="width:100px;text-align:center">' + this.taxonomie + '</td></tr>';
                    });
                    html += '</table>'
                    sel.append(html);
                }
             });
        });
    });
</script>

<div id="content-main">
    <h1>Objectifs particuliers et objectifs évaluateurs</h1>
    <select id="obp_selector">
        {% for obj in object_list %}
            <option value={{obj.id}}>{{obj.code}} - {{obj.nom}}</option>
        {% endfor %}
    </select >
    <table >
        <tr>
            <th width="100px">Code</th><th width="800px">Nom</th>
            <th style="width:100px;text-align:center">Taxonomie</th>
        </tr>
    </table>
    <div id="json"></div>
</div>
{% endblock %}